// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7GaW7M79hlvopXBDxzHHse4oE70SK_QM',
    appId: '1:429018063802:web:8bf6007dfc741075757383',
    messagingSenderId: '429018063802',
    projectId: 'noreply-officina',
    authDomain: 'noreply-officina.firebaseapp.com',
    storageBucket: 'noreply-officina.firebasestorage.app',
    measurementId: 'G-R7BK86MR4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8T54MJJJpnFWVeVpZhFjfB9qPs9su470',
    appId: '1:429018063802:android:e72b38c456bd12d7757383',
    messagingSenderId: '429018063802',
    projectId: 'noreply-officina',
    storageBucket: 'noreply-officina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUeYXozC1LIVZYoJ89ABCA-YLFyfs9ty4',
    appId: '1:429018063802:ios:19367691256c568d757383',
    messagingSenderId: '429018063802',
    projectId: 'noreply-officina',
    storageBucket: 'noreply-officina.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

}